### ISSUE TITLE
List.GetItemAtIndex should work with negative indices.

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/DynamoWishlist#187]
## What improvement/feature would you like to see in Dynamo?
Negative indicies less than the length of the index should pull from the end of the list.

## How would you see this improvement/feature working? 
![image](https://user-images.githubusercontent.com/29869395/103568708-0622c380-4e94-11eb-8049-c9f34b178259.png) this would return the last item in the list.

**Comment by andydandy74** [comment]
@Amoursol @JacobSmall Just noticed the PR for this issue. Have the repercussions on existing graphs been considered? The ```GetItemAtIndex``` node is often used in conjunction with the ```IndexOf``` node. Currently that node will return ```-1``` for items not found in the list. So what I envision happening in existing graphs is that instead of returning ```null``` for items not in the list we will now see the last item in the list returned in such cases:
![grafik](https://github.com/DynamoDS/DynamoWishlist/assets/3014437/11205e50-da5a-4f7f-8555-78c6ddef116a)
Would it perhaps make sense to have the ```IndexOf``` node return null instead of ```-1``` for items not found in the list in the future?

**Comment by QilongTang** [comment]
@andydandy74 You are right on the expected result
![image](https://github.com/DynamoDS/DynamoWishlist/assets/3942418/dc832c0a-80ba-42aa-bac3-f94dec8b2d96)

@Amoursol I think the proposed change on `IndexOf` node makes more sense after the negative index support, what do you think?

**Comment by andydandy74** [comment]
Proposed change see https://github.com/DynamoDS/Dynamo/pull/15268

**Comment by Amoursol** [comment]
@QilongTang Returning null works for me!

**Comment by mjkkirschner** [comment]
@QilongTang @avidit - perhaps it's worth taking a sec to consider other approaches like adding a new node with this behavior.
We know that returning null and passing it downstream creates its own issues.
Additionally it seems like we're missing some test cases that combine using the two nodes.
